### ISSUE TITLE
Integrate topic_view.php and feed.php

### ISSUE THREAD

**Issue by thomaskise** [thomaskise/itc250-winter2019-p4-News-Aggregator#17]
feed.php uses topid (/feed.php?topid=1)

topic_view.php uses id

this needs to be resolve

**Comment by ejmcreates** [comment]
I've actually solved this in my version of feed

**Comment by thomaskise** [comment]
Cool. So we can close it when we merge the change.

**Comment by ejmcreates** [comment]
solved with recent pull request
